[build-system]
requires = ["setuptools>=80.0"]
build-backend = "setuptools.build_meta"

[project]
name = "project1"
version = "0.0.1"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2",
    "pandas>=2",
    "scipy>=1",
]

[tool.setuptools.packages.find]
where = ["src"]
